version: '3.1'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3.9.4-management
    restart: always
    ports:
      - '5672:5672' # RabbitMQ ana bağlantı noktası
      - '15672:15672' # Yönetici arayüzü için bağlantı noktası
    environment:
      RABBITMQ_DEFAULT_USER: guest # Kullanıcı adı
      RABBITMQ_DEFAULT_PASS: 12345*x # Parola

  redis:
    image: redis
    restart: always
    ports:
      - '5679:6379'
    command: redis-server --requirepass mypassword*1xw

  python-app:
    build:
      context: ./pythonta
      dockerfile: dockerfile
    volumes:
      - ./pythonta:/app
    depends_on:
      - mongodb
      - rabbitmq
      - redis

  node-app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '5000:5000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
      - rabbitmq
      - redis
      - python-app

volumes:
  mongodb_data:
